name: "update leaderboard"

on:
  schedule:
    # Runs every 5 minutes
    - cron: "5/5 * * * *"

  push:
    branches: [ "master" ]

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - run: yarn
    - run: yarn "leaderboard:triggerNextCrawl"
      env:
        HUBSPOT_SECRET: ${{ secrets.HUBSPOT_SECRET }}
        GOERLI_API_KEY: ${{ secrets.GOERLI_API_KEY }}
        SEPOLIA_API_KEY: ${{ secrets.SEPOLIA_API_KEY }}
        ARB_GOERLI_API_KEY: ${{ secrets.ARB_GOERLI_API_KEY }}
        OPT_GOERLI_API_KEY: ${{ secrets.OPT_GOERLI_API_KEY }}
        MUMBAI_API_KEY: ${{ secrets.MUMBAI_API_KEY }}
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force_with_lease: true